# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 23:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160226_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='course',
            name='slots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 2, 26, 23, 12, 28, 230573, tzinfo=utc), max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
