# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160226_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='speakers',
            field=models.ManyToManyField(to='core.Speaker'),
        ),
    ]
