# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 21:17
from __future__ import unicode_literals

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()

def forward_course_abc_to_mti(apps, schema_editor):
    """
    - Para cada ABC(Abstract Base Class), instanciar um
        MTI(Model Table Inheritance) com todos os atributos
    - Salvar o MTI
    - Associar os speakers do ABC no MTI
    - Deletar o ABC
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )

def backward_course_abc_to_mti(apps, schema_editor):
    """
    - Para cada ABC(Abstract Base Class), instanciar um
        MTI(Model Table Inheritance) com todos os atributos
    - Salvar o MTI
    - Associar os speakers do ABC no MTI
    - Deletar o ABC
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti,
                             backward_course_abc_to_mti)
    ]
